### ISSUE TITLE
Resim ekle

### ISSUE THREAD

**Issue by uzeyir-yariz** [HamzaBabaa/restaurant-proje-update-0.2#1]
# TODO

- [ ] resimleri ekle
- [ ] resimleri boyutlandır 
- [ ] açılır menü araştır 
- [ ] hataları temizle 
- [ ] renk uyumu sağla
- [ ] mobil uyumluluk araştır
